### ISSUE TITLE
BUILD Failed on Android

### ISSUE THREAD

**Issue by dreson4** [react-native-seoul/react-native-kakao-logins#8]
I keep getting this error, seems like there's a problem with the support library used in this library

```
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:font
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontStyle
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontWeight
```

**Comment by dreson4** [comment]
Ok, so it turns out its the problem with Kakao SDK V 1.11.1 which is included in the library.
So I changed to 1.5.1 and had to rewrite a lot of code in the RNKakaoLoginsModule.java file
Now it works

**Comment by dooboolab** [comment]
@dreson4 This issue is related to `com.android.support:support-v7` version mismatch in your environment. Please refer to [here](https://github.com/mauron85/react-native-background-geolocation/issues/116). 
Check if you have something like `compile 'com.android.support:appcompat-v7:27.0.2` in your build.gradle.
